<?php

$LANG['share_config_description'] = 'Share-indstillinger';
$LANG['/share/blocks/github_share.inc-human'] = 'Github';
$LANG['/share/blocks/facebook_likebox.inc-human'] = 'Facebook synes godt-om';
$LANG['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook Ligesom Box JS';
$LANG['/share/blocks/google_plusone.inc-human'] = 'Google+';
$LANG['/share/blocks/facebook_share.inc-human'] = 'Facebook del';
