<?php

$_COS_LANG_MODULE['share_config_description'] = 'Share-indstillinger';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = 'Github';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = 'Facebook synes godt-om';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook Ligesom Box JS';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = 'Google+';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = 'Facebook del';
