<?php

$_COS_LANG_MODULE['share_main_menu_title'] = '共享';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = '谷歌 1';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = 'Facebook分享';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = 'Facebook的Likebox';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = 'Github上共享盒';
$_COS_LANG_MODULE['share_stack_text'] = '分享一个链接到这个上';
