<?php


// Translation of file /modules/share/system_lang.inc

$_COS_LANG_MODULE['share_config_description'] = 'share_config_description';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = '/share/blocks/github_share.inc-human';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = '/share/blocks/facebook_likebox.inc-human';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox_js.inc-human'] = '/share/blocks/facebook_likebox_js.inc-human';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = '/share/blocks/google_plusone.inc-human';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = '/share/blocks/facebook_share.inc-human';
