<?php


// Translation of file /modules/share/system_lang.inc

$_COS_LANG_MODULE['share_config_description'] = 'Share settings';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = 'Github star box';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = 'Facebook like box';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = 'Google+';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = 'Facebook share';
