<?php

$_COS_LANG_MODULE['share_config_description'] = 'Del innstillinger';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = 'Github stjerners boks';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = 'Facebook liker boks';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook som boksen JS';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = 'Google ';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = 'Facebook aksje';
