<?php

$LANG['share_config_description'] = 'Del innstillinger';
$LANG['/share/blocks/github_share.inc-human'] = 'Github stjerners boks';
$LANG['/share/blocks/facebook_likebox.inc-human'] = 'Facebook liker boks';
$LANG['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook som boksen JS';
$LANG['/share/blocks/google_plusone.inc-human'] = 'Google ';
$LANG['/share/blocks/facebook_share.inc-human'] = 'Facebook aksje';
