<?php

$LANG['share_config_description'] = 'Teilen Einstellungen';
$LANG['/share/blocks/github_share.inc-human'] = 'Github-Sterne-Box';
$LANG['/share/blocks/facebook_likebox.inc-human'] = 'Facebook ist wie eine Schachtel';
$LANG['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook wie eine Schachtel JS';
$LANG['/share/blocks/google_plusone.inc-human'] = 'Google ';
$LANG['/share/blocks/facebook_share.inc-human'] = 'Facebook-Aktien';
