<?php

$_COS_LANG_MODULE['share_config_description'] = 'Teilen Einstellungen';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = 'Github-Sterne-Box';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = 'Facebook ist wie eine Schachtel';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook wie eine Schachtel JS';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = 'Google ';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = 'Facebook-Aktien';
