<?php

$_COS_LANG_MODULE['share_main_menu_title'] = 'Osuus';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = 'Google  1';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = 'Facebook Jaa';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = 'Facebook Likebox';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = 'Github';
$_COS_LANG_MODULE['share_stack_text'] = 'Jaa tämä';
