<?php

$LANG['share_config_description'] = 'Jakoasetukset';
$LANG['/share/blocks/github_share.inc-human'] = 'Github tähden box';
$LANG['/share/blocks/facebook_likebox.inc-human'] = 'Facebook kuten ruutuun';
$LANG['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook kuten ruutuun JS';
$LANG['/share/blocks/google_plusone.inc-human'] = 'Google ';
$LANG['/share/blocks/facebook_share.inc-human'] = 'Facebook Jaa';
