<?php

$_COS_LANG_MODULE['share_config_description'] = 'Dela inställningar';
$_COS_LANG_MODULE['/share/blocks/github_share.inc-human'] = 'Github stjärna låda';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox.inc-human'] = 'Facebook som låda';
$_COS_LANG_MODULE['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook liknande låda JS';
$_COS_LANG_MODULE['/share/blocks/google_plusone.inc-human'] = 'Google ';
$_COS_LANG_MODULE['/share/blocks/facebook_share.inc-human'] = 'Facebook andel';
