<?php

$LANG['share_config_description'] = 'Dela inställningar';
$LANG['/share/blocks/github_share.inc-human'] = 'Github stjärna låda';
$LANG['/share/blocks/facebook_likebox.inc-human'] = 'Facebook som låda';
$LANG['/share/blocks/facebook_likebox_js.inc-human'] = 'Facebook liknande låda JS';
$LANG['/share/blocks/google_plusone.inc-human'] = 'Google ';
$LANG['/share/blocks/facebook_share.inc-human'] = 'Facebook andel';
